feat: настройка тестов + CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,3 +30,35 @@ jobs:
 
       - name: Ruff - check style
         run: ruff check .
+
+  test:
+    runs-on: ubuntu-latest
+    needs: lint
+    services:
+      docker:
+        image: docker:24.0.5
+        options: --privileged
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Docker Compose
+        run: |
+          docker compose version
+
+      - name: Run tests with Docker Compose
+        run: |
+          docker compose -p taskflow_test -f docker-compose.test.yml --env-file .env.test up -d --build
+
+          # Ждем завершения web-test
+          docker wait taskflow_web_test
+
+          # Получаем exit code тестов
+          EXIT_CODE=$(docker inspect taskflow_web_test --format='{{.State.ExitCode}}')
+
+          # Выключаем и удаляем все контейнеры и тома
+          docker compose -f docker-compose.test.yml down --volumes --remove-orphans
+
+          # Выходим с кодом тестов
+          exit $EXIT_CODE
